# Dependabot configuration for AI Code Assistant Pro
# Automatically keeps dependencies up to date for security and performance
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor npm dependencies (TypeScript, VS Code Extension dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    # Limit number of open PRs to avoid overwhelming
    open-pull-requests-limit: 5
    # Group VS Code and TypeScript related updates
    groups:
      vscode:
        patterns:
          - "@types/vscode"
          - "@vscode/*"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "*test*"
          - "*jest*"
          - "*mocha*"
        update-types:
          - "minor"
          - "patch"
    # Automatically merge minor and patch updates for development dependencies
    assignees:
      - "msalsouri"
    reviewers:
      - "msalsouri"
    # Custom commit message
    commit-message:
      prefix: "⬆️ deps"
      prefix-development: "⬆️ deps-dev"
      include: "scope"
    # Only update production dependencies on weekdays
    # Development dependencies can be updated more frequently
    labels:
      - "dependencies"
      - "security"
    # Ignore major version updates for stability (handle manually)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Allow Dependabot to update lockfiles
    versioning-strategy: "increase"

  # Monitor GitHub Actions if we add any workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
    assignees:
      - "msalsouri"
    reviewers:
      - "msalsouri"
    commit-message:
      prefix: "⬆️ actions"
      include: "scope"
    labels:
      - "github-actions"
      - "ci-cd"
