#!/bin/bash

echo "🤖 AI Code Assistant Pro - Personality Testing"
echo "=============================================="
echo ""
echo "✅ Your Current Models:"
ollama list
echo ""
echo "🎯 Quick Test Commands:"
echo ""
echo "1. ⚡ Test Buzzy (Performance):"
echo "   Prompt: 'Optimize this loop: for i in range(1000000): result.append(i * 2)'"
echo ""
echo "2. 🔨 Test Builder (Architecture):"
echo "   Prompt: 'Design microservices for e-commerce'"
echo ""
echo "3. 🔍 Test Scout (Code Quality):"
echo "   Prompt: 'Review this function: def calc(x, y): return x + y if x > 0 else y'"
echo ""
echo "4. 🛡️ Test Guardian (Security):"
echo "   Prompt: 'Check for SQL injection: SELECT * FROM users WHERE id = \${userId}'"
echo ""
echo "📊 Expected Model Usage:"
echo "• Code tasks (Buzzy, Scout, Guardian) → codellama:7b"
echo "• Analysis tasks (Builder, Spark, Scribe) → dolphin-mixtral:8x7b"
echo ""
echo "🚀 To test: Click robot icon in VS Code activity bar!"